language: r
cache: packages
cran: http://cran.rstudio.com
dist: bionic

os:
  - linux
  - osx
  
r:
  - oldrel
  - release
  - devel

jobs:
  exclude:
  - r: devel
    os: osx
   
r_packages:
  - devtools
  - covr
  - testthat

script:
  - R CMD build .
  - R CMD check *.tar.gz --as-cran
  
after_success:
  - >-
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_R_VERSION_STRING" = "release" ]; then
      echo Code coverage...
      Rscript -e 'covr::codecov()'
    else
      echo Skip code coverage
    fi 
